// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropamaPOS.Data;

#nullable disable

namespace PropamaPOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024052033_EstadoCompra")]
    partial class EstadoCompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropamaPOS.Models.AjusteInventario", b =>
                {
                    b.Property<int>("Id_Ajuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ajuste"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id_Ajuste");

                    b.HasIndex("Id_Empleado");

                    b.ToTable("AjustesInventario");
                });

            modelBuilder.Entity("PropamaPOS.Models.AjusteInventarioDetalle", b =>
                {
                    b.Property<int>("Id_AjusteDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_AjusteDetalle"));

                    b.Property<int>("CantidadPresentaciones")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<int>("Id_Ajuste")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int?>("Id_ItemPresentacion")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockAntes")
                        .HasColumnType("int");

                    b.Property<int>("StockDespues")
                        .HasColumnType("int");

                    b.HasKey("Id_AjusteDetalle");

                    b.HasIndex("Id_Ajuste");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_ItemPresentacion");

                    b.ToTable("AjusteInventarioDetalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PropamaPOS.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Cliente");

                    b.HasIndex("NIT")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.Property<int>("Id_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Compra"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCompra")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Compra");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("Id_Proveedor");

                    b.HasIndex("NumeroCompra")
                        .IsUnique();

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("PropamaPOS.Models.CompraDetalle", b =>
                {
                    b.Property<int>("Id_CompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraDetalle"));

                    b.Property<int>("CantidadPresentaciones")
                        .HasColumnType("int");

                    b.Property<int>("Id_Compra")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_ItemPresentacion")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCostoPorPresentacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCostoPorUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CompraDetalle");

                    b.HasIndex("Id_Compra");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_ItemPresentacion");

                    b.ToTable("CompraDetalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Empleado", b =>
                {
                    b.Property<int>("Id_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Empleado");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.Property<int>("Id_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Item"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("CostoPromedioUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Id_Categoria")
                        .HasColumnType("int");

                    b.Property<bool>("IsServicio")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id_Item");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Id_Categoria");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemPresentacion", b =>
                {
                    b.Property<int>("Id_ItemPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ItemPresentacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_UnidadMedida")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_ItemPresentacion");

                    b.HasIndex("Id_UnidadMedida");

                    b.HasIndex("Id_Item", "Id_UnidadMedida")
                        .IsUnique();

                    b.ToTable("ItemPresentaciones");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemProveedor", b =>
                {
                    b.Property<int>("Id_ItemProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ItemProveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.HasKey("Id_ItemProveedor");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("ItemProveedores");
                });

            modelBuilder.Entity("PropamaPOS.Models.PagoVenta", b =>
                {
                    b.Property<int>("Id_PagoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PagoVenta"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("int");

                    b.Property<int>("Metodo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_PagoVenta");

                    b.HasIndex("Id_Venta");

                    b.ToTable("PagoVentas");
                });

            modelBuilder.Entity("PropamaPOS.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PropamaPOS.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Proveedor");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("PropamaPOS.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PropamaPOS.Models.ServicioComponente", b =>
                {
                    b.Property<int>("Id_ServicioComponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ServicioComponente"));

                    b.Property<decimal>("CantidadPorServicio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_Servicio")
                        .HasColumnType("int");

                    b.HasKey("Id_ServicioComponente");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_Servicio");

                    b.ToTable("ServicioComponentes");
                });

            modelBuilder.Entity("PropamaPOS.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id_UnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_UnidadMedida"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_UnidadMedida");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("ContraHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Rol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PropamaPOS.Models.Venta", b =>
                {
                    b.Property<int>("Id_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Venta"));

                    b.Property<decimal>("AjusteRedondeo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Descuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Empleado")
                        .HasColumnType("int");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoRecibido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreConsumidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroVenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Venta");

                    b.HasIndex("Id_Cliente");

                    b.HasIndex("Id_Empleado");

                    b.HasIndex("NumeroVenta")
                        .IsUnique();

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PropamaPOS.Models.VentaDetalle", b =>
                {
                    b.Property<int>("Id_VentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_VentaDetalle"));

                    b.Property<int>("CantidadPresentaciones")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EsServicio")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int?>("Id_ItemPresentacion")
                        .HasColumnType("int");

                    b.Property<int>("Id_Venta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioVentaPorPresentacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_VentaDetalle");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_ItemPresentacion");

                    b.HasIndex("Id_Venta");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.AjusteInventario", b =>
                {
                    b.HasOne("PropamaPOS.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PropamaPOS.Models.AjusteInventarioDetalle", b =>
                {
                    b.HasOne("PropamaPOS.Models.AjusteInventario", "Ajuste")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Ajuste")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.ItemPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("Id_ItemPresentacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ajuste");

                    b.Navigation("Item");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.HasOne("PropamaPOS.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PropamaPOS.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PropamaPOS.Models.CompraDetalle", b =>
                {
                    b.HasOne("PropamaPOS.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.ItemPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("Id_ItemPresentacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Item");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("PropamaPOS.Models.Empleado", b =>
                {
                    b.HasOne("PropamaPOS.Models.Usuario", "Usuario")
                        .WithOne("Empleado")
                        .HasForeignKey("PropamaPOS.Models.Empleado", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.HasOne("PropamaPOS.Models.Categoria", "Categoria")
                        .WithMany("Items")
                        .HasForeignKey("Id_Categoria")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemPresentacion", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany("Presentaciones")
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("Id_UnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemProveedor", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PropamaPOS.Models.PagoVenta", b =>
                {
                    b.HasOne("PropamaPOS.Models.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PropamaPOS.Models.PasswordResetToken", b =>
                {
                    b.HasOne("PropamaPOS.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PropamaPOS.Models.ServicioComponente", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "ItemConsumido")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Item", "Servicio")
                        .WithMany()
                        .HasForeignKey("Id_Servicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemConsumido");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.HasOne("PropamaPOS.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PropamaPOS.Models.Venta", b =>
                {
                    b.HasOne("PropamaPOS.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Id_Cliente")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PropamaPOS.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Id_Empleado")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("PropamaPOS.Models.VentaDetalle", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.ItemPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("Id_ItemPresentacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropamaPOS.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Venta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Presentacion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PropamaPOS.Models.AjusteInventario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Categoria", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.Navigation("Empleado")
                        .IsRequired();
                });

            modelBuilder.Entity("PropamaPOS.Models.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
