// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropamaPOS.Data;

#nullable disable

namespace PropamaPOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251009020334_ModuloCompras")]
    partial class ModuloCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropamaPOS.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Cliente");

                    b.HasIndex("Nombre", "Apellido", "Telefono")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.Property<int>("Id_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Compra"));

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Compra");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("PropamaPOS.Models.CompraDetalle", b =>
                {
                    b.Property<int>("Id_CompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraDetalle"));

                    b.Property<int>("CantidadPresentaciones")
                        .HasColumnType("int");

                    b.Property<int>("Id_Compra")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_ItemPresentacion")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCostoPorPresentacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioCostoPorUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CompraDetalle");

                    b.HasIndex("Id_Compra");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_ItemPresentacion");

                    b.ToTable("CompraDetalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Empleado", b =>
                {
                    b.Property<int>("Id_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Empleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Empleado");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.Property<int>("Id_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Item"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostoPromedioUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Id_Proveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id_Item");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemPresentacion", b =>
                {
                    b.Property<int>("Id_ItemPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ItemPresentacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_UnidadMedida")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_ItemPresentacion");

                    b.HasIndex("Id_UnidadMedida");

                    b.HasIndex("Id_Item", "Id_UnidadMedida")
                        .IsUnique();

                    b.ToTable("ItemPresentaciones");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemProveedor", b =>
                {
                    b.Property<int>("Id_ItemProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ItemProveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Item")
                        .HasColumnType("int");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.HasKey("Id_ItemProveedor");

                    b.HasIndex("Id_Item");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("ItemProveedores");
                });

            modelBuilder.Entity("PropamaPOS.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("PropamaPOS.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Proveedor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id_Proveedor");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("PropamaPOS.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PropamaPOS.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id_UnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_UnidadMedida"));

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_UnidadMedida");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("ContraHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Rol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.HasOne("PropamaPOS.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PropamaPOS.Models.CompraDetalle", b =>
                {
                    b.HasOne("PropamaPOS.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Compra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.ItemPresentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("Id_ItemPresentacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Item");

                    b.Navigation("Presentacion");
                });

            modelBuilder.Entity("PropamaPOS.Models.Empleado", b =>
                {
                    b.HasOne("PropamaPOS.Models.Usuario", "Usuario")
                        .WithOne("Empleado")
                        .HasForeignKey("PropamaPOS.Models.Empleado", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.HasOne("PropamaPOS.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemPresentacion", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany("Presentaciones")
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("Id_UnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("PropamaPOS.Models.ItemProveedor", b =>
                {
                    b.HasOne("PropamaPOS.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropamaPOS.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PropamaPOS.Models.PasswordResetToken", b =>
                {
                    b.HasOne("PropamaPOS.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.HasOne("PropamaPOS.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PropamaPOS.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PropamaPOS.Models.Item", b =>
                {
                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("PropamaPOS.Models.Usuario", b =>
                {
                    b.Navigation("Empleado")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
